image: alpine:latest

variables:
  TARGET: "dilemme_prisonnier"

stages:
  - test
  - build
  - pages
  - deploy

pages:
  image: alpine:latest
  stage: pages
  script: 
  - apk add doxygen graphviz ghostscript-fonts
  - doxygen Doxyfile
  - mv webdoc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
  - tags
  - gitlab-ci-test

build-linux:
  image: alpine:latest
  stage: build
  script: 
  - apk add build-base cmake ninja
  - mkdir build
  - cd build
  - cmake -Gninja ..
  - ninja
  artifacts:
    paths:
      - bin/${TARGET}_client
      - bin/${TARGET}_server
      - bin/server.properties
    expire_in: 1 week
  only:
  - master
  - tags
  - gitlab-ci-test

test-docs:
  image: alpine:latest
  stage: test
  script:
  - apk add doxygen graphviz ghostscript-fonts
  - doxygen Doxyfile

test-build-linux:
  image: alpine:latest
  stage: build
  script:
  - apk add build-base cmake ninja
  - mkdir build
  - cd build
  - cmake -Gninja ..
  - ninja
  except:
  - master
  - tags
  - gitlab-ci-test

production:
  type: deploy
  dependencies:
    - build-linux
    - pages
  script:
    - echo "0"
  artifacts:
    name: "${TARGET}"
    paths:
      - ./
    expire_in: 1 year
  only:
  - tags
  - gitlab-ci-test

production-master:
  type: deploy
  dependencies:
    - build-linux
    - pages
  script:
    - echo "0"
  artifacts:
    name: "${TARGET}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - ./
    expire_in: 1 year
  only:
  - master
  - gitlab-ci-test
