Dilemme_Prisonnier: project/src/server/model/joueur.c File Reference
joueur.c File Reference
Contient et manipule les informations à propos du joueur.
#include "joueur.h"
#include <error_handler.h>
#include <ligne.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
struct Joueur * creerJoueur (char *pseudo)
Crée et initialise un struct Joueur.
void detruireJoueur (struct Joueur *joueur)
Supprime le Joueur et libère la mémoire.
struct ListeJoueurs * creerListeJoueurs (void)
Crée et initialise une liste de Joueurs.
void ajouterJoueur (struct ListeJoueurs *liste_joueurs, struct Joueur *joueur)
Ajoute un Joueur à la liste de Joueurs.
char * popJoueur (struct ListeJoueurs *liste_joueurs)
Ejecte un Joueur tel un LIFO.
char * popJoueurParPseudo (struct ListeJoueurs *liste_joueurs, char *pseudo)
Ejecte un Joueur précis.
enum EtatJoueur popJoueurParEtat (struct ListeJoueurs *liste_joueurs, enum EtatJoueur etat)
Ejecte un Joueur par ETAT.
int popJoueurParCanal (struct ListeJoueurs *liste_joueurs, int canal)
Ejecte un Joueur précis par canal.
struct Joueur * trouverJoueurParPseudo (struct ListeJoueurs *liste_joueurs, char *pseudo)
Trouve un Joueur précis.
void detruireListeJoueurs (struct ListeJoueurs *liste_joueurs)
Supprime les Joueurs, la liste de Joueurs et libère la mémoire.
struct ListeJoueurs * clonerListeJoueurs (struct ListeJoueurs *liste_joueurs)
Clone les Joueurs et la liste de Joueurs.
void broadcastAutreJoueurs (struct Joueur *joueur, char *texte)
Transmet un texte à tous les joueurs.
void broadcastJoueurs (struct ListeJoueurs *liste_joueurs, char *texte)
Transmet un texte à tous les joueurs.
char sontPretListeJoueurs (struct ListeJoueurs *liste_joueurs)
Retourne si les Joueurs sont prêts.
void setScoreListeJoueurs (struct ListeJoueurs *liste_joueurs, long score)
Set le score de tous les Joueurs de la liste de Joueurs.
void setEtatListeJoueurs (struct ListeJoueurs *liste_joueurs, enum EtatJoueur etat)
Set l'état de tous les Joueurs de la liste de Joueurs.
void setChoixListeJoueurs (struct ListeJoueurs *liste_joueurs, enum ChoixJoueur choix)
Set le choix de tous les Joueurs de la liste de Joueurs.
Detailed Description
Contient et manipule les informations à propos du joueur.
Les structures permettent la manipulation des données du Joueur et éventuellement d'une liste de Joueurs.
Fonctionnalités :
Créer et supprimer un Joueur
Créer, supprimer, pop, clone, trouver dans une liste de Joueurs
Check le status PRET dans la liste de Joueurs
Set le Score, Choix, Etat de tous les Joueur dans la liste de Joueurs
Usage:
struct Joueur* joueur = creerJoueur("PSEUDO");
struct ListeJoueurs* liste_joueurs = creerListeJoueurs();
ajouterJoueur(liste_joueurs, joueur);
struct ListeJoueurs* copie_liste_joueurs = clonerListeJoueurs(liste_joueurs);
struct Joueur* joueur_found = trouverJoueurParPseudo(liste_joueurs,
"PSEUDO");
char* pseudo = popJoueur(liste_joueurs);
char* pseudo = popJoueurParPseudo(liste_joueurs, "PSEUDO");
detruireListeJoueurs(liste_joueurs);
Author
Marc NGUYEN
Thomas LARDY
Date
20 Mai 2019
Definition in file joueur.c.
Function Documentation
ajouterJoueur()
void ajouterJoueur (struct ListeJoueurs * liste_joueurs, struct Joueur * joueur)
Ajoute un Joueur à la liste de Joueurs.
Ajoute à la liste tel un LIFO, c'est-à-dire :
NULL<-...<-Joueur<-HEAD
=> NULL<-...<-Joueur<-Joueur ajoutée<-HEAD
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
joueur Pointer vers la struct Joueur.
Definition at line 93 of file joueur.c.
{
   joueur->prev = NULL;
   joueur->next = liste_joueurs->HEAD;
   if (joueur->next != NULL) joueur->next->prev = joueur;
   liste_joueurs->HEAD = joueur;
   liste_joueurs->nb_joueurs++;
 }
References ListeJoueurs::HEAD, ListeJoueurs::nb_joueurs, Joueur::next, and Joueur::prev.
Referenced by clonerListeJoueurs().
broadcastAutreJoueurs()
void broadcastAutreJoueurs (struct Joueur * joueur, char * texte)
Transmet un texte à tous les joueurs.
Envoie du texte dans le canal des joueur dans la liste de joueurs.
Parameters
joueur Pointeur vers la structure joueur
texte Chaine de caractère
Definition at line 282 of file joueur.c.
{
   struct Joueur* joueurDroite = joueur->next;
   struct Joueur* joueurGauche = joueur->prev;
   char texte_final[BUFSIZ];
   snprintf(texte_final, BUFSIZ, "%s> %s\n", joueur->pseudo, texte);
   while (joueurDroite != NULL) {
     ecrireLigne(joueurDroite->canal, texte_final);
     joueurDroite = joueurDroite->next;
   }
   while (joueurGauche != NULL) {
     ecrireLigne(joueurGauche->canal, texte_final);
     joueurGauche = joueurGauche->prev;
   }
   // printf("[BROADCAST] Complete\n");
 }
References Joueur::canal, Joueur::next, Joueur::prev, and Joueur::pseudo.
broadcastJoueurs()
void broadcastJoueurs (struct ListeJoueurs * liste_joueurs, char * texte)
Transmet un texte à tous les joueurs.
Envoie du texte à tout le monde.
Parameters
liste_joueurs Pointeur vers la liste de Joueurs
texte Chaine de caractère
Definition at line 306 of file joueur.c.
{
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   while (pJoueur != NULL) {
     ecrireLigne(pJoueur->canal, texte);
     pJoueur = pJoueur->next;
   }
 }
References Joueur::canal, ListeJoueurs::HEAD, and Joueur::next.
Referenced by afficherScoreListeJoueurs(), and deroulement().
clonerListeJoueurs()
struct ListeJoueurs* clonerListeJoueurs (struct ListeJoueurs * liste_joueurs)
Clone les Joueurs et la liste de Joueurs.
Les Joueurs clonées ont de nouvelles mémoires allouées. Pour trouver le Joueur original, utiliser trouverJoueurParPseudo sur la liste originale.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
Returns
struct ListeJoueurs* Pointer vers la struct ListeJoueurs clonée.
Definition at line 262 of file joueur.c.
{
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   struct Joueur* nouveau_joueur;
   struct ListeJoueurs* copie_liste_joueurs = creerListeJoueurs();
   while (pJoueur->next != NULL) pJoueur = pJoueur->next;  // Aller à la fin
   while (pJoueur != NULL) {                               // Réplication
     nouveau_joueur = creerJoueur(pJoueur->pseudo);
     ajouterJoueur(copie_liste_joueurs, nouveau_joueur);
     pJoueur = pJoueur->prev;
   }
   return copie_liste_joueurs;
 }
References ajouterJoueur(), creerJoueur(), creerListeJoueurs(), ListeJoueurs::HEAD, Joueur::next, Joueur::prev, and Joueur::pseudo.
creerJoueur()
struct Joueur* creerJoueur (char * pseudo)
Crée et initialise un struct Joueur.
joueur->choix = RIEN; joueur->etat = NOT_PRET; joueur->pseudo = pseudo; sem_init(&joueur->state_sem, 0, 0);
Parameters
pseudo Pseudonyme du Joueur.
Returns
struct Joueur* Pointer vers la struct Joueur.
Definition at line 52 of file joueur.c.
{
   struct Joueur* joueur = (struct Joueur*)malloc(sizeof(struct Joueur));
   joueur->choix = RIEN;
   joueur->etat = NOT_PRET;
   joueur->pseudo = pseudo;
   return joueur;
 }
References Joueur::choix, Joueur::etat, and Joueur::pseudo.
Referenced by clonerListeJoueurs().
creerListeJoueurs()
struct ListeJoueurs* creerListeJoueurs (void)
Crée et initialise une liste de Joueurs.
Liste chaînée de type LIFO.
Returns
struct ListeJoueurs* Pointer vers la struct ListeJoueurs.
Definition at line 74 of file joueur.c.
{
   struct ListeJoueurs* liste_joueurs =
       (struct ListeJoueurs*)malloc(sizeof(struct ListeJoueurs));
   liste_joueurs->nb_joueurs = 0;
   liste_joueurs->HEAD = NULL;
   return liste_joueurs;
 }
References ListeJoueurs::HEAD, and ListeJoueurs::nb_joueurs.
Referenced by clonerListeJoueurs(), and creerDC().
detruireJoueur()
void detruireJoueur (struct Joueur * joueur)
Supprime le Joueur et libère la mémoire.
Parameters
joueur Pointer vers la struct Joueur.
Definition at line 65 of file joueur.c.
 { free(joueur); }
Referenced by detruireListeJoueurs(), popJoueur(), popJoueurParCanal(), popJoueurParEtat(), and popJoueurParPseudo().
detruireListeJoueurs()
void detruireListeJoueurs (struct ListeJoueurs * liste_joueurs)
Supprime les Joueurs, la liste de Joueurs et libère la mémoire.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
Definition at line 238 of file joueur.c.
{
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   struct Joueur* next;
   if (pJoueur != NULL) {
     next = liste_joueurs->HEAD->next;
     while (next != NULL) {
       next = pJoueur->next;
       detruireJoueur(pJoueur);
       pJoueur = next;
     }
   }
   free(liste_joueurs);
 }
References detruireJoueur(), ListeJoueurs::HEAD, and Joueur::next.
popJoueur()
char* popJoueur (struct ListeJoueurs * liste_joueurs)
Ejecte un Joueur tel un LIFO.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
Returns
char* Pseudonyme du Joueur éjecté.
Definition at line 107 of file joueur.c.
{
   if (liste_joueurs->nb_joueurs < 1) erreur("Tentative de pop aucun joueur !");
   char* pseudo = liste_joueurs->HEAD->pseudo;
   struct Joueur* next = liste_joueurs->HEAD->next;
   detruireJoueur(liste_joueurs->HEAD);
   liste_joueurs->HEAD = next;
   if (next != NULL) next->prev = NULL;
   liste_joueurs->nb_joueurs--;
   return pseudo;
 }
References detruireJoueur(), ListeJoueurs::HEAD, ListeJoueurs::nb_joueurs, Joueur::next, Joueur::prev, and Joueur::pseudo.
popJoueurParCanal()
int popJoueurParCanal (struct ListeJoueurs * liste_joueurs, int canal)
Ejecte un Joueur précis par canal.
-1 = Erreur.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
canal Canal du Joueur à éjecter
Returns
int Canal du Joueur éjecté
Definition at line 192 of file joueur.c.
{
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   struct Joueur* next;
   int canal_return = -1;
   while (pJoueur != NULL) {
     if (pJoueur->canal == canal) {
       next = pJoueur->next;
       if (pJoueur->prev == NULL)
         liste_joueurs->HEAD = next;
       else
         pJoueur->prev->next = next;
       if (next != NULL) next->prev = pJoueur->prev;
       canal_return = pJoueur->canal;
       detruireJoueur(pJoueur);
       liste_joueurs->nb_joueurs--;
       return canal_return;
     }
     pJoueur = pJoueur->next;
   }
   return canal_return;
 }
References Joueur::canal, detruireJoueur(), ListeJoueurs::HEAD, ListeJoueurs::nb_joueurs, Joueur::next, and Joueur::prev.
popJoueurParEtat()
enum EtatJoueur popJoueurParEtat (struct ListeJoueurs * liste_joueurs, enum EtatJoueur etat)
Ejecte un Joueur par ETAT.
Ejecte un Joueur par Etat.
NONE = Not found.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
etat Etat du Joueur à éjecter
Returns
EtatJoueur Etat du Joueur éjecté
Definition at line 159 of file joueur.c.
{
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   struct Joueur* next;
   enum EtatJoueur etat_return = NONE;
   while (pJoueur != NULL) {
     if (pJoueur->etat == etat) {
       next = pJoueur->next;
       if (pJoueur->prev == NULL)
         liste_joueurs->HEAD = next;
       else
         pJoueur->prev->next = next;
       if (next != NULL) next->prev = pJoueur->prev;
       etat_return = pJoueur->etat;
       detruireJoueur(pJoueur);
       liste_joueurs->nb_joueurs--;
       return etat_return;
     }
     pJoueur = pJoueur->next;
   }
   return etat_return;
 }
References detruireJoueur(), Joueur::etat, ListeJoueurs::HEAD, ListeJoueurs::nb_joueurs, Joueur::next, and Joueur::prev.
Referenced by deroulement().
popJoueurParPseudo()
char* popJoueurParPseudo (struct ListeJoueurs * liste_joueurs, char * pseudo)
Ejecte un Joueur précis.
NULL = Erreur.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
pseudo Pseudonyme du Joueur à éjecter
Returns
char* Pseudonyme du Joueur éjecté
Definition at line 127 of file joueur.c.
{
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   struct Joueur* next;
   char* pseudo_return = NULL;
   while (pJoueur != NULL) {
     if (strcmp(pJoueur->pseudo, pseudo) == 0) {
       next = pJoueur->next;
       if (pJoueur->prev == NULL)
         liste_joueurs->HEAD = next;
       else
         pJoueur->prev->next = next;
       if (next != NULL) next->prev = pJoueur->prev;
       pseudo_return = pJoueur->pseudo;
       detruireJoueur(pJoueur);
       liste_joueurs->nb_joueurs--;
       return pseudo_return;
     }
     pJoueur = pJoueur->next;
   }
   return pseudo_return;
 }
References detruireJoueur(), ListeJoueurs::HEAD, ListeJoueurs::nb_joueurs, Joueur::next, Joueur::prev, and Joueur::pseudo.
setChoixListeJoueurs()
void setChoixListeJoueurs (struct ListeJoueurs * liste_joueurs, enum ChoixJoueur choix)
Set le choix de tous les Joueurs de la liste de Joueurs.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
choix Choix des Joueurs.
Definition at line 375 of file joueur.c.
{
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   while (pJoueur != NULL) {
     pJoueur->choix = choix;
     pJoueur = pJoueur->next;
   }
 }
References Joueur::choix, ListeJoueurs::HEAD, and Joueur::next.
setEtatListeJoueurs()
void setEtatListeJoueurs (struct ListeJoueurs * liste_joueurs, enum EtatJoueur etat)
Set l'état de tous les Joueurs de la liste de Joueurs.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
etat Etat des Joueurs.
Definition at line 359 of file joueur.c.
{
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   while (pJoueur != NULL) {
     pJoueur->etat = etat;
     pJoueur = pJoueur->next;
   }
 }
References Joueur::etat, ListeJoueurs::HEAD, and Joueur::next.
Referenced by deroulement().
setScoreListeJoueurs()
void setScoreListeJoueurs (struct ListeJoueurs * liste_joueurs, long score)
Set le score de tous les Joueurs de la liste de Joueurs.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
score Score des Joueurs.
Definition at line 344 of file joueur.c.
{
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   while (pJoueur != NULL) {
     pJoueur->score = score;
     pJoueur = pJoueur->next;
   }
 }
References ListeJoueurs::HEAD, Joueur::next, and Joueur::score.
Referenced by deroulement().
sontPretListeJoueurs()
char sontPretListeJoueurs (struct ListeJoueurs * liste_joueurs)
Retourne si les Joueurs sont prêts.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
Returns
char Boolean.
Definition at line 321 of file joueur.c.
{
   int i = 0;
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   while (pJoueur != NULL) {
     if (pJoueur->etat != PRET1 && pJoueur->etat != PRET2)
       return 0;
     else
       i++;
     pJoueur = pJoueur->next;
   }
   if (i > 1)
     return 1;
   else
     return 0;
 }
References Joueur::etat, ListeJoueurs::HEAD, and Joueur::next.
Referenced by deroulement().
trouverJoueurParPseudo()
struct Joueur* trouverJoueurParPseudo (struct ListeJoueurs * liste_joueurs, char * pseudo)
Trouve un Joueur précis.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
pseudo Pseudonyme du Joueur à trouver.
Returns
struct Joueur* Pointer vers la struct Joueur trouvé.
Definition at line 222 of file joueur.c.
{
   struct Joueur* pJoueur = liste_joueurs->HEAD;
   while (pJoueur != NULL) {
     if (strcmp(pJoueur->pseudo, pseudo) == 0) return pJoueur;
     pJoueur = pJoueur->next;
   }
   return NULL;
 }
References ListeJoueurs::HEAD, Joueur::next, and Joueur::pseudo.