Dilemme_Prisonnier: project/src/server/deroulement/match_thread.c File Reference
match_thread.c File Reference
Fonctions permettant le fonctionnement des parties.
#include "match_thread.h"
#include <error_handler.h>
#include <ligne.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "../model/datacontext.h"
#include "../view/joueur_view.h"
Functions
void creerMatchWorkers (struct ListeMatches *liste_matches)
Créer tout les workers pour chaque matches.
void joinMatchWorkers (struct ListeMatches *liste_matches)
Attends la fin de chaque match.
Detailed Description
Fonctions permettant le fonctionnement des parties.
Chaque match est géré par un thread.
Le match attend d'abord que les joueurs sont PRET2.
Il envoie ensuite une notification et attend un /start
Ensuite se lance la boucle de match.
Chaque joueur a le choix entre /trahir et /coop.
Author
Marc NGUYEN
Thomas LARDY
Date
20 Mai 2019
Definition in file match_thread.c.
Function Documentation
creerMatchWorkers()
void creerMatchWorkers (struct ListeMatches * liste_matches)
Créer tout les workers pour chaque matches.
Parameters
liste_matches Pointer vers la liste de matches.
Definition at line 44 of file match_thread.c.
{
   for (long i = 0; i < liste_matches->nb_matches; i++) {
     if (pthread_create(&liste_matches->matches[i]->pthread_id, NULL,
                        _matchThread, liste_matches->matches[i]) != 0)
       erreur_IO("pthread_create");
   }
 }
References DC::liste_matches, ListeMatches::matches, ListeMatches::nb_matches, and Match::pthread_id.
Referenced by deroulement().
joinMatchWorkers()
void joinMatchWorkers (struct ListeMatches * liste_matches)
Attends la fin de chaque match.
Parameters
liste_matches Pointer vers la liste de matches.
Definition at line 57 of file match_thread.c.
{
   // TODO: Afficher ce que ressorte les threads
   for (long i = 0; i < liste_matches->nb_matches; i++) {
     if (pthread_join(liste_matches->matches[i]->pthread_id, NULL) != 0)
       erreur_IO("pthread_join");
   }
   detruireListeMatch(liste_matches);
 }
References detruireListeMatch(), DC::liste_matches, ListeMatches::matches, ListeMatches::nb_matches, and Match::pthread_id.
Referenced by deroulement().