Dilemme_Prisonnier: project/src/server/model/match.c File Reference
match.c File Reference
Gère la logique des matches.
#include "match.h"
#include <error_handler.h>
#include <stdlib.h>
Functions
struct ListeMatches * creerListeMatch (struct ListeJoueurs *liste_joueurs)
Créer une liste de matches en fonction d'une liste de joueurs.
void detruireListeMatch (struct ListeMatches *liste_matches)
Supprime ListeMatches et libère la mémoire.
Detailed Description
Gère la logique des matches.
Author
Marc NGUYEN
Thomas LARDY
Date
20 Mai 2019
Definition in file match.c.
Function Documentation
creerListeMatch()
struct ListeMatches* creerListeMatch (struct ListeJoueurs * liste_joueurs)
Créer une liste de matches en fonction d'une liste de joueurs.
Premièrement, on reserve Comb(nb_joueurs, 2) matches. Ensuite, on clone la liste de joueurs. On utilise pop la liste de joueurs clonée afin de parcourir la liste tel une combinaison.
Schématiquement, ça donne : ABCD[E]
^^^^
||||
E
ABC[D]
^^^
|||
D
AB[C]
^^
||
C
A[B]
^
|
B
Chaque flèche représente un match.
Parameters
liste_joueurs Pointer vers la struct ListeJoueurs.
Returns
struct ListeMatches* Pointer vers la struct ListeMatches.
Definition at line 77 of file match.c.
{
   struct ListeMatches* liste_matches =
       (struct ListeMatches*)malloc(sizeof(struct ListeMatches*));
   long nb_matches = _factorielle(liste_joueurs->nb_joueurs) /
                     (_factorielle(liste_joueurs->nb_joueurs - 2) * 2);
   struct Match** matches =
       (struct Match**)malloc(sizeof(struct Match*) * nb_matches);
   struct ListeJoueurs* copie_liste_joueurs = clonerListeJoueurs(liste_joueurs);
   struct Joueur *joueur1, *joueur2 = NULL;
   struct Joueur* pJoueur;
   char* pseudo = NULL;
   long match = 0;
   while (copie_liste_joueurs->HEAD != NULL) {
     pseudo = popJoueur(copie_liste_joueurs);
     joueur1 = trouverJoueurParPseudo(liste_joueurs, pseudo);
     pJoueur = copie_liste_joueurs->HEAD;
     while (pJoueur != NULL) {
       joueur2 = trouverJoueurParPseudo(liste_joueurs, pJoueur->pseudo);
       matches[match] = _creerMatch(joueur1, joueur2);
       match++;
       pJoueur = pJoueur->next;
     }
   }
   liste_matches->nb_matches = nb_matches;
   liste_matches->matches = matches;
   return liste_matches;
 }
References ListeMatches::nb_matches.
Referenced by deroulement().
detruireListeMatch()
void detruireListeMatch (struct ListeMatches * liste_matches)
Supprime ListeMatches et libère la mémoire.
Parameters
liste_matches Pointer vers la struct ListeMatches.
Definition at line 113 of file match.c.
{
   for (long i = 0; i < liste_matches->nb_matches; i++) {
     _detruireMatch(liste_matches->matches[i]);
   }
   free(liste_matches);
 }
References ListeMatches::nb_matches.
Referenced by deroulement(), and joinMatchWorkers().